### ISSUE TITLE
review of material on 10/16/18

### ISSUE THREAD

**Issue by bqtrinh** [Microsoft/MCW-SAP-HANA-on-Azure#10]
Document>> https://github.com/Microsoft/MCW-SAP-HANA-on-Azure/blob/sept-2018-update/Hands-on%20lab/HOL%20step-by-step%20-%20SAP%20HANA%20on%20Azure.md#task-3-create-the-primary-and-the-secondary-sites

- steps 1 and 4, command: su -- s03adm  (typo, only 1 '-' )

Document>> https://github.com/Microsoft/MCW-SAP-HANA-on-Azure/blob/sept-2018-update/Hands-on%20lab/HOL%20step-by-step%20-%20SAP%20HANA%20on%20Azure.md#task-1-create-an-azure-ad-application-for-the-stonith-device

- Both SUSE and MS now are recommending the use of SBD for fencing instead of Azure service principal due to the expediency of SBD fencing.  We are recently talking about removing the Azure service principal fendinc section of the doc here:   https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#default-pacemaker-configuration-for-sbd.  I would suggest to switch to the SBD fencing mechanism.

- same comment for the 'HOL unguided - SAP HANA on Azure.md' process

Document>> on the reference-slides deck

- slides 22, 23 need update to refeckt M series VMs are now certified including some of the fractional M's.  please reference the updated SAP note 1928533.

- slide #30, for the non production storage layout, using 1x P20 or 1x P10 may offer lower IOPS than to stripe 2x or 3x premium disks into one logical volume.  Examples can be seen here>>  https://github.com/AzureCAT-GSI/Hana-Test-Deploy/tree/master/sap-hana-cluster

**Comment by polichtm** [comment]
resolving #10

**Comment by polichtm** [comment]
completed
