### ISSUE TITLE
Error while setting up SAP HANA Database System Replication

### ISSUE THREAD

**Issue by PraveenAnil** [Microsoft/MCW-SAP-HANA-on-Azure#11]
I was running this command in Exercise 5 Task 3 Step 3: 
hdbnsutil -sr_enable --name=SITE1
I got this error
![image](https://user-images.githubusercontent.com/7903608/48774028-0cbf4280-ecef-11e8-846a-9c118beb0e2f.png)

But I had followed and executed all the steps as per the doc here: https://github.com/Microsoft/MCW-SAP-HANA-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20SAP%20HANA%20on%20Azure.md

**Comment by polichtm** [comment]
pls use the updated instructions (December 2018)
