### ISSUE TITLE
September Update - QC results

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-SAP-HANA-on-Azure#12]
WDS trainer presentation (PPT) - Alt-text needs to be more descriptive.  "Common solutions for the case study." and "Diagram of the BW on HANA with HA preferred solution." is not enough information.

WDS Student & Trainer guides - Alt-text needs to be more descriptive.  "Common solutions for the case study." and "Diagram of the BW on HANA with HA preferred solution." is not enough information.

Step-by-step & unguided labs - No Solution architecture included.

Please review issues #10 & #11 to see if Sept update resolved and comment/close as appropriate.

**Comment by polichtm** [comment]
completed
