### ISSUE TITLE
ha-cluster-join

### ISSUE THREAD

**Issue by FrankFoese** [Microsoft/MCW-SAP-HANA-on-Azure#15]
actually I try to work through your HOL SAP on Azure. 
It is really great but unfortunately I run into a problem and I hope you might help…or know somebody… 😉

The problem occurs in exercise 3 / task 1 “configure clustering”. Task 1, step 1 works well without any problems. But when I start task 1, step 2 “ha-cluster-join“ the procedure stops with the following error:

 see 
![error1](https://user-images.githubusercontent.com/46990122/51664502-cff71c80-1fb9-11e9-9c07-49bbe2900907.png)

I tried the following so far:

1.	I could ping both cluster nodes via IP and hostname
2.	I analyzed ha-cluster-bootstrap.log … I could find the following error:

 
![error2](https://user-images.githubusercontent.com/46990122/51664519-da191b00-1fb9-11e9-8563-a7386a9063bd.png)

3.	I checked the mentioned files (csync2.cfg and key_hagroup) on the primary node….files are there
4.	I run the command  “scp root@s03-db-0:'/etc/csync2/{csync2.cfg,key_hagroup}' /etc/csync2” separately with the following error:
 
![error3](https://user-images.githubusercontent.com/46990122/51664532-e309ec80-1fb9-11e9-98f7-1874d666283a.png)

But when I split the command into two separate parts…then scp command is working:

scp root@s03-db-0:'/etc/csync2/csync2.cfg’ /etc/csync2
scp root@s03-db-0:'/etc/csync2/key_hagroup' /etc/csync2

it seems that there might be an syntax error in the script!?!

…but at this point my linux-knowledge comes to an end 😉. I have no idea how to fix it to finish the step ha-cluster-join successfully. I would really appreciate any idea you may have.

Thanks
Frank

**Comment by Jeff-Opsgility** [comment]
Thanks Frank, we're looking into it.

**Comment by DawnmarieDesJardins** [comment]
@FrankFoese 
Hi Frank,  I gave our authors your email address so they can contact you directly to troubleshoot with you.
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue, handled via email.
