### ISSUE TITLE
sp creation task gave error messages: Changing "hanav1snsp01" to a valid URI of "http://hanav1snsp01", which is the required format used for service principal names

### ISSUE THREAD

**Issue by kevinzhang8888** [microsoft/MCW-SAP-HANA-on-Azure#19]
HANA_SP_NAME='hanav1snsp01'
HANA_SP_ID=$(az ad sp list --display-name $HANA_SP_NAME --query "[0].appId" --output tsv)
if ! [ -z "$HANA_SP_ID" ]
then
    az ad sp delete --id $HANA_SP_ID
fi
HANA_SP=$(az ad sp create-for-rbac --name $HANA_SP_NAME)

got following error:
Changing "hanav1snsp01" to a valid URI of "http://hanav1snsp01", which is the required format used for service principal names

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @polichtm 
Hello,
Please review & advise.
Thanks, Dawnmarie

**Comment by paulopsgility** [comment]
@kevinzhang8888 were you able to proceed beyond this? @polichtm and I discussed and this is an informational message not technically an error.

**Comment by DawnmarieDesJardins** [comment]
@kevinzhang8888 @paulopsgility 
Hi Kevin,
Closing this issue as resolved since we have not heard back from you.  Please feel free to reopen if necessary.
Thanks! Dawnmarie
