### ISSUE TITLE
Error: Unsupported block type

### ISSUE THREAD

**Issue by worldquest** [microsoft/MCW-SAP-HANA-on-Azure#21]
Hi Team,

Does anyone faced the error with Unsupported block type ? 

~/sap-hana/deploy/vm/modules/ha_pair$ terraform plan

Error: Unsupported block type

  on ../common_setup/main.tf line 30, in module "vnet":
  30:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign i

~/sap-hana/deploy/vm/modules/ha_pair/.terraform/modules/common_setup.vnet/Azure-terraform-azurerm-vnet-e0b9155$ vi main.tf 

resource "azurerm_virtual_network" "vnet" {
  name                = "${var.vnet_name}"
  location            = "${var.location}"
  address_space       = ["${var.address_space}"]
  resource_group_name = "${azurerm_resource_group.vnet.name}"
  dns_servers         = "${var.dns_servers}"
  tags                = "${var.tags}"

**Comment by paulopsgility** [comment]
@worldquest We are looking into this.

**Comment by DawnmarieDesJardins** [comment]
@worldquest @paulopsgility 
Hi CJ.  Apologies for the delayed response, we've not been able to find a fix for your issue.  Since the lab is not currently working, we've archived the documents until we can update the material.  We hope to have a corrected lab back up in Q4.
