### ISSUE TITLE
Disk "hanav1ha32355-iscsi-disk0": Code="InternalExecutionError" Message="An internal execution error occurred. Please retrylater."

### ISSUE THREAD

**Issue by worldquest** [microsoft/MCW-SAP-HANA-on-Azure#26]
Hi team,

i was applying HA TF form and end up with the below error. 

From the hannav1ha-RG   : Disk status showed Failed.  

Any fix can done somewhere?

Error: Error waiting for Virtual Machine "hanav1ha32355-iscsi" (Resource Group "hanav1ha-RG") to finish updating Disk "hanav1ha32355-iscsi-disk0": Code="InternalExecutionError" Message="An internal execution error occurred. Please retrylater."

  on ../generic_vm_and_disk_creation/main.tf line 36, in resource "azurerm_virtual_machine_data_disk_attachment" "disk":
  36: resource "azurerm_virtual_machine_data_disk_attachment" "disk" {

Error: Code="InternalExecutionError" Message="An internal execution error occurred. Please retry later."

  on ../generic_vm_and_disk_creation/main.tf line 45, in resource "azurerm_virtual_machine" "vm":
  45: resource "azurerm_virtual_machine" "vm" {

Error: Code="InternalExecutionError" Message="An internal execution error occurred. Please retry later."

  on ../generic_vm_and_disk_creation/main.tf line 45, in resource "azurerm_virtual_machine" "vm":
  45: resource "azurerm_virtual_machine" "vm" {

**Comment by paulopsgility** [comment]
@worldquest are you saying you have a failed disk resource or a deployment failed?

**Comment by DawnmarieDesJardins** [comment]
@worldquest 
Hi CJ.  Are you still having trouble with running this lab?  If not, I'll close the issue as resolved.
Thank you!

**Comment by cjpark-sapcsa** [comment]
Hi Team, 

I am not sure anyone change the script line, but i tried again after deletion of deployed resources, i managed to by pass the disk creation error.  Please close the issue

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete.  Disk passed creation error.
