### ISSUE TITLE
Terraform template seems incorrect

### ISSUE THREAD

**Issue by iamalexmang** [microsoft/MCW-SAP-HANA-on-Azure#33]
It seems that the Terraform template contains 
```
<html><body>You are being <a href="https://github.com/polichtm/MCW-SAP-HANA-on-Azure/blob/master/Hands-on%20lab/labfiles/sap-hana/templates/template-sn1.json">redirected</a>.</body></html>
```
rather than containing a valid template. The URL highlighted in above is likely the correct content, but without that content, the instructions fail when it comes to:
```
terraform_v2.sh plan template-sn1
```
That is step 15 on Task 1.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #34
