### ISSUE TITLE
Issues with SAP HANA Cluster instance deployment using Ansible

### ISSUE THREAD

**Issue by fasalzaman** [microsoft/MCW-SAP-HANA-on-Azure#41]
![DeploymentError](https://user-images.githubusercontent.com/29173745/145253627-7a960a86-ea07-4713-8c9e-3f14160d6d20.png)
We are facing issues in alternate deployments of Hana instance deployment using Ansible. Can we get this checked

**Comment by KitSkin** [comment]
I've tried a few different deployments of this and have not been able to duplicate the failed communication yet.  Have you been able to verify that the VNet Peering is enabled between the 10.100.0.0 and the 10.101.0.0 VNets, and that the NSG on the relevant subnets are configured to allow the communications between both environments?

**Comment by fasalzaman** [comment]
We figured out lates that this also happened due to some issues in the terraform deployment. Some of the configuration in terraform deployment didnt happen correctly. Can we have the required fix available for Highly-available Azure infrastructure terraform deployment. I have raised another issue : https://github.com/microsoft/MCW-SAP-HANA-on-Azure/issues/42 . Can we please fix the issues  in terraform deployment. We are not getting these issues in all the deployments. This is only happening for 30% of the deployments.

**Comment by DawnmarieDesJardins** [comment]
Added Kit as assignee since he's been reviewing as well.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #45 - lab documents have been archived.
